services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - storage:/rails/storage
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_TO_STDOUT=1
    depends_on:
      - jobs
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  jobs:
    build: .
    volumes:
      - storage:/rails/storage
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_TO_STDOUT=1
    command: ["./bin/jobs"]

volumes:
  storage:
